PREFIX : @schemaUri

CONSTRUCT {
    [ :value ?firstLetter ]
}
WHERE {
    SELECT DISTINCT ?firstLetter
    WHERE {
        ?s
            a :Group ;
            :groupName ?groupName .

        BIND(UCASE(SUBSTR(?groupName, 1, 1)) AS ?firstLetter)
    }
}