PREFIX : @schemaUri

CONSTRUCT {
  ?group
    a :group;
    :groupName ?groupName;
    :groupStartDate ?groupStartDate.
 }

WHERE {
  BIND (@group_id as ?group)

  ?group a :Group.

  OPTIONAL { ?group :groupName ?groupName . }
  OPTIONAL { ?group :groupStartDate ?groupStartDate . }
}
