PREFIX : @schemaUri

CONSTRUCT {
  ?group
    a :Group;
    :groupName ?groupName;
    :groupStartDate ?groupStartDate;
    :groupEndDate ?groupEndDate.
 }

WHERE {
  ?group a :Group.
  
  OPTIONAL { ?group :groupName ?groupName . }
  OPTIONAL { ?group :groupStartDate ?groupStartDate . }
  OPTIONAL { ?group :groupEndDate ?groupEndDate . }
} 
