PREFIX : <http://id.ukpds.org/schema/>

CONSTRUCT {
    [ :value ?firstLetter ] .
    @houseid
        a :House ;
        :houseName ?houseName .
    @partyid
        a :Party ;
        :partyName ?partyName .
}
WHERE {
    SELECT DISTINCT ?houseName ?partyName ?firstLetter
    WHERE {
        BIND(@houseid AS ?house)
        BIND(@partyid AS ?party)

        ?house
            :houseName ?houseName .
        ?party
            :partyName ?partyName .
        ?person
            a :Member ;
            <http://example.com/A5EE13ABE03C4D3A8F1A274F57097B6C> ?listAs ;
            :partyMemberHasPartyMembership ?partyMembership .
        ?partyMembership :partyMembershipHasParty ?party .
        ?incumbency :incumbencyHasMember ?person .

        {
            ?incumbency :houseIncumbencyHasHouse ?house .
        }
        UNION {
            ?incumbency :seatIncumbencyHasHouseSeat ?seat .
            ?seat :houseSeatHasHouse ?house .
        }

        BIND(UCASE(SUBSTR(?listAs, 1, 1)) AS ?firstLetter)
    }
}
