PREFIX : @schemaUri
CONSTRUCT {
    ?house
        a :House ;
        :houseName ?houseName ;
        :houseHasFormalBody ?formalBody ;
        :formalBodyStartDate ?formalBodyStartDate ;
        :formalBodyEndDate ?formalBodyEndDate .

    ?formalBody
        a :FormalBody ;
        :formalBodyName ?formalBodyName .
}
WHERE {
    BIND(@house_id AS ?house)
    ?house
        a :House ;
        :houseName ?houseName .
    ?formalBody
        a :FormalBody ;
        :formalBodyName ?formalBodyName ;
        :formalBodyStartDate ?formalBodyStartDate ;
        :formalBodyEndDate ?formalBodyEndDate .
}
