PREFIX : @schemaUri
CONSTRUCT {
    ?s a @type .
}
WHERE {
    BIND(@type AS ?type)
    BIND(@source AS ?source)
    BIND(@id AS ?id)

    ?s
        a @type ;
        ?source ?actualId .

    FILTER(STR(?actualId) = ?id)
}
