PREFIX : @schemaUri
CONSTRUCT {
    _:x :value ?firstLetter .
    ?party
    	a :Party ;
    	:partyName ?partyName .
}
WHERE {
	{
	    SELECT DISTINCT ?firstLetter
	    WHERE {
	        BIND(@party_id AS ?party)
	        ?party
	            a :Party ;
	            :partyHasPartyMembership ?partyMembership ;
	            :partyName ?partyName .
	        ?partyMembership :partyMembershipHasPartyMember ?person .
	        ?person <http://example.com/A5EE13ABE03C4D3A8F1A274F57097B6C> ?listAs .
	        BIND(ucase(SUBSTR(?listAs, 1, 1)) as ?firstLetter)
	    }
  }
  UNION
  {
  	BIND(@party_id AS ?party)
    ?party
    	a :Party ;
    	:partyName ?partyName .
	}
}
