PREFIX : @schemaUri
CONSTRUCT {
    _:x :value ?firstLetter .
    ?party
    	a :Party ;
    	:partyName ?partyName .
}
WHERE {
	{
    SELECT DISTINCT ?firstLetter
    WHERE {
        BIND(@party_id AS ?party)
        ?party
            a :Party ;
            :partyName ?partyName ;
            :partyHasPartyMembership ?partyMembership .
        FILTER NOT EXISTS { ?partyMembership a :PastPartyMembership . }
        ?partyMembership :partyMembershipHasPartyMember ?person .
        ?person :memberHasParliamentaryIncumbency ?incumbency .
		?incumbency a :SeatIncumbency .
		FILTER NOT EXISTS { ?incumbency a :PastParliamentaryIncumbency . }
		FILTER NOT EXISTS {
			?incumbency :incumbencyHasIncumbencyInterruption ?interruption.
			FILTER NOT EXISTS {
				?interruption :endDate ?end.
			}
		}
		?person <http://example.com/A5EE13ABE03C4D3A8F1A274F57097B6C> ?listAs .
        BIND(ucase(SUBSTR(?listAs, 1, 1)) as ?firstLetter)
    }
  }
  UNION
  {
    BIND(@party_id AS ?party)
	?party
	    a :Party ;
	    :partyName ?partyName ;
  }
}
