PREFIX : @schemaUri
CONSTRUCT {
    ?party
        a :Party ;
        :partyName ?partyName ;
    	:count ?memberCount .
    ?parliament
        a :ParliamentPeriod ;
        :parliamentPeriodStartDate ?parliamentPeriodStartDate ;
        :parliamentPeriodEndDate ?parliamentPeriodEndDate .
    ?speaker
        a :Person .
}
WHERE {
    { SELECT ?party ?partyName (COUNT(?member) AS ?memberCount) WHERE {
    ?party a :Party ;
        :partyName ?partyName ;
    	:partyHasPartyMembership ?partyMembership .
        FILTER NOT EXISTS { ?partyMembership a :PastPartyMembership . }
        ?partyMembership :partyMembershipHasPartyMember ?member .
        ?member :memberHasIncumbency ?seatIncumbency .
        ?seatIncumbency a :SeatIncumbency .
        FILTER NOT EXISTS { ?seatIncumbency a :PastIncumbency . }
	}
    GROUP BY ?party ?partyName
}
    UNION {
        SELECT * WHERE {
            ?parliament a :ParliamentPeriod ;
   			    :parliamentPeriodStartDate ?parliamentPeriodStartDate ;
                OPTIONAL { ?parliament :parliamentPeriodEndDate ?parliamentPeriodEndDate . }
        }
        ORDER BY DESC(?parliamentPeriodStartDate)
        LIMIT 3
    }
    UNION {
        SELECT ?speaker WHERE {
            ?speaker :partyMemberHasPartyMembership ?partyMembership .
            FILTER NOT EXISTS { ?partyMembership a :PastPartyMembership . }
            ?partyMembership :partyMembershipHasParty ?party .
            ?party :partyName "Speaker" .
        }
    }
}
