PREFIX : @schemaUri

CONSTRUCT {
    ?procedure
        a :Procedure ;
        :procedureName ?procedureName .
}
WHERE {
    BIND (@procedure_id AS ?procedure)

    ?procedure :procedureName ?procedureName .
}
