PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
	?domain ?property ?range, ?rangeLiteral .
	?class rdfs:subClassOf ?superClass.
}
FROM <http://www.ontotext.com/explicit>
WHERE
{
	{
		?property
			a owl:ObjectProperty ;
			rdfs:range ?range .
	}
	UNION
	{
		?property
			a owl:DatatypeProperty ;
			rdfs:range ?dataTypeRange.

		BIND(STR(?dataTypeRange) AS ?rangeLiteral)
	}

	?property rdfs:domain ?domain.
	?class rdfs:subClassOf ?superClass.
}