PREFIX : @schemaUri

CONSTRUCT {
    ?statutoryInstrumentPaper a :StatutoryInstrumentPaper .
}
WHERE {
    BIND(@property AS ?property)
    BIND(@value AS ?value)

    ?statutoryInstrumentPaper
        a :StatutoryInstrumentPaper ;
        ?property ?actualValue .

        FILTER(STR(?actualValue) = ?value)
}
