PREFIX : @schemaUri

CONSTRUCT {
	?statutoryInstrumentPaper
		a :StatutoryInstrumentPaper, :LaidThing, :WorkPackagedThing ;
		:laidThingName ?laidThingName ;
		:laidThingHasLaying ?laying ;
    	:workPackagedThingHasWorkPackage ?workPackage .
	?laying
		a :Laying ;
		:layingDate ?layingDate ;
    	:layingHasLayingBody ?layingBody .
  	?layingBody
    	a :Group ;
    	:groupName ?groupName .
  	?workPackage
    	a :WorkPackage ;
    	:workPackageHasProcedure ?procedure .
  	?procedure
    	a :Procedure ;
    	:procedureName ?procedureName .
}
WHERE {
    ?statutoryInstrumentPaper a :StatutoryInstrumentPaper .

	OPTIONAL { ?statutoryInstrumentPaper :laidThingName ?laidThingName . }

	OPTIONAL {
		?statutoryInstrumentPaper :laidThingHasLaying ?laying .
		OPTIONAL { ?laying :layingDate ?layingDate . }
    	OPTIONAL {
      		?laying :layingHasLayingBody ?layingBody .
      		OPTIONAL { ?layingBody :groupName ?groupName . }
    	}
	}
  	OPTIONAL {
    	?statutoryInstrumentPaper :workPackagedThingHasWorkPackage ?workPackage .
    	OPTIONAL {
      		?workPackage :workPackageHasProcedure ?procedure .
      		OPTIONAL { ?procedure :procedureName ?procedureName . }
    	}
  	}
}
