PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : @schemaUri

CONSTRUCT {
  ?statutoryInstrumentPaper 
    	a :ProposedNegativeStatutoryInstrumentPaper ;
    	:proposedNegativeStatutoryInstrumentPaperName ?proposedNegativeStatutoryInstrumentPaperName ;
    	:laidThingHasLaying ?laying . 	
  ?workPackage
    	a :WorkPackage ;
  		:workPackageHasWorkPackagedThing ?statutoryInstrumentPaper .
  ?laying
    	a :Laying ;
  		:layingDate ?layingDate .
}
WHERE {
  ?statutoryInstrumentPaper a :ProposedNegativeStatutoryInstrumentPaper ;
  							:workPackagedThingHasWorkPackage ?workPackage .
  OPTIONAL { ?statutoryInstrumentPaper :proposedNegativeStatutoryInstrumentPaperName ?proposedNegativeStatutoryInstrumentPaperName . }
  OPTIONAL { 
    ?statutoryInstrumentPaper :laidThingHasLaying ?laying . 
  	?laying :layingDate ?layingDate . 
  } 
}