PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : @schemaUri

CONSTRUCT {
  ?statutoryInstrumentPaper 
    	a :StatutoryInstrumentPaper ;
    	:statutoryInstrumentPaperName ?statutoryInstrumentPaperName ;
    	:laidThingHasLaying ?laying . 	
  ?workPackage
    	a :WorkPackage ;
  		:workPackageHasWorkPackagedThing ?statutoryInstrumentPaper .
  ?laying
    	a :Laying ;
  		:layingDate ?layingDate .
}
WHERE {
  ?statutoryInstrumentPaper a :StatutoryInstrumentPaper ;
  							:workPackagedThingHasWorkPackage ?workPackage .
  OPTIONAL { ?statutoryInstrumentPaper :statutoryInstrumentPaperName ?statutoryInstrumentPaperName . }
  OPTIONAL { 
    ?statutoryInstrumentPaper :laidThingHasLaying ?laying . 
  	?laying :layingDate ?layingDate . 
  }
}